XI_TLS_LIB_INC_DIR ?= ./src/import/tls/wolfssl/
XI_TLS_LIB_BIN_DIR ?= ./src/import/tls/wolfssl/src/.libs/
XI_TLS_LIB_NAME ?= wolfssl

XI_CONFIG_FLAGS += -DOCSP_STAPLING
XI_CONFIG_FLAGS += -DHAVE_CERTIFICATE_STATUS_REQUEST
XI_CONFIG_FLAGS += -DTLSLIB_WOLFSSL
