# Copyright (c) 2003-2018, LogMeIn, Inc. All rights reserved.
#
# This is part of the Xively C Client library,
# it is licensed under the BSD 3-Clause license.

XI_EXAMPLE_NAME := firmware_update

include ../common/rules.mk
include ../common/targets.mk
