# Copyright (c) 2003-2018, LogMeIn, Inc. All rights reserved.
#
# This is part of the Xively C Client library,
# it is licensed under the BSD 3-Clause license.

XI_EXAMPLE_NAME := senml_serializer

XI_FLAGS_INCLUDE += -I$(CURDIR)/../../include_senml

include ../common/rules.mk
include ../common/targets.mk
