/* Copyright (c) 2003-2018, LogMeIn, Inc. All rights reserved.
 *
 * This is part of the Xively C Client library,
 * it is licensed under the BSD 3-Clause license.
 */

#ifndef __XI_CBOR_CODEC_CT_KEYS_H__
#define __XI_CBOR_CODEC_CT_KEYS_H__


#define XI_CBOR_CODEC_CT_STRING_MSGTYPE "msgtype"
#define XI_CBOR_CODEC_CT_STRING_MSGVER "msgver"
#define XI_CBOR_CODEC_CT_STRING_LIST "list"
#define XI_CBOR_CODEC_CT_STRING_FILE_NAME "N"
#define XI_CBOR_CODEC_CT_STRING_FILE_REVISION "R"

#define XI_CBOR_CODEC_CT_STRING_FILE_OPERATION "O"
#define XI_CBOR_CODEC_CT_STRING_FILE_IMAGESIZE "S"
#define XI_CBOR_CODEC_CT_STRING_FILE_FINGERPRINT "F"
#define XI_CBOR_CODEC_CT_STRING_FILE_DOWNLOADLINK "L"
#define XI_CBOR_CODEC_CT_STRING_FILE_MQTT_DL_SUPPORTED "M"

#define XI_CBOR_CODEC_CT_STRING_FILECHUNK_OFFSET "O"
#define XI_CBOR_CODEC_CT_STRING_FILECHUNK_LENGTH "L"
#define XI_CBOR_CODEC_CT_STRING_FILECHUNK_STATUS "S"
#define XI_CBOR_CODEC_CT_STRING_FILECHUNK_CHUNK "C"

#define XI_CBOR_CODEC_CT_STRING_FILESTATUS_PHASE "P"
#define XI_CBOR_CODEC_CT_STRING_FILESTATUS_CODE "S"


#endif /* __XI_CBOR_CODEC_CT_KEYS_H__ */
