# Copyright (c) 2003-2016, LogMeIn, Inc. All rights reserved.
#
# This is part of the Xively C Client library,
# it is licensed under the BSD 3-Clause license.

XI_EXAMPLE_NAME := mqtt_last_will

include ../common/rules.mk
include ../common/targets.mk
