/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: control_topic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "control_topic.pb-c.h"
void   ct__rpc__header__init
                     (CTRPC__Header         *message)
{
  static CTRPC__Header init_value = CT__RPC__HEADER__INIT;
  *message = init_value;
}
void   ct__rpc__response__init
                     (CTRPC__Response         *message)
{
  static CTRPC__Response init_value = CT__RPC__RESPONSE__INIT;
  *message = init_value;
}
void   ct__rpc__snd_creds__init
                     (CTRPC__SndCreds         *message)
{
  static CTRPC__SndCreds init_value = CT__RPC__SND_CREDS__INIT;
  *message = init_value;
}
void   ct__rpc__req_asc_nonce__init
                     (CTRPC__ReqAscNonce         *message)
{
  static CTRPC__ReqAscNonce init_value = CT__RPC__REQ_ASC_NONCE__INIT;
  *message = init_value;
}
void   ct__rpc__req_asc_nonce_resp__init
                     (CTRPC__ReqAscNonceResp         *message)
{
  static CTRPC__ReqAscNonceResp init_value = CT__RPC__REQ_ASC_NONCE_RESP__INIT;
  *message = init_value;
}
void   ct__rpc__asc_window__init
                     (CTRPC__AscWindow         *message)
{
  static CTRPC__AscWindow init_value = CT__RPC__ASC_WINDOW__INIT;
  *message = init_value;
}
void   ct__rpc__set_certs__init
                     (CTRPC__SetCerts         *message)
{
  static CTRPC__SetCerts init_value = CT__RPC__SET_CERTS__INIT;
  *message = init_value;
}
void   ct__rpc__add_cert__init
                     (CTRPC__AddCert         *message)
{
  static CTRPC__AddCert init_value = CT__RPC__ADD_CERT__INIT;
  *message = init_value;
}
void   ct__rpc__set_bckoff__init
                     (CTRPC__SetBckoff         *message)
{
  static CTRPC__SetBckoff init_value = CT__RPC__SET_BCKOFF__INIT;
  *message = init_value;
}
void   ct__rpc__set_serv_list__init
                     (CTRPC__SetServList         *message)
{
  static CTRPC__SetServList init_value = CT__RPC__SET_SERV_LIST__INIT;
  *message = init_value;
}
void   ct__rpc__log_mode__init
                     (CTRPC__LogMode         *message)
{
  static CTRPC__LogMode init_value = CT__RPC__LOG_MODE__INIT;
  *message = init_value;
}
void   ct__rpc__init
                     (CTRPC         *message)
{
  static CTRPC init_value = CT__RPC__INIT;
  *message = init_value;
}
size_t ct__rpc__get_packed_size
                     (const CTRPC *message)
{
  assert(message->base.descriptor == &ct__rpc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ct__rpc__pack
                     (const CTRPC *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ct__rpc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ct__rpc__pack_to_buffer
                     (const CTRPC *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ct__rpc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTRPC *
       ct__rpc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTRPC *)
     protobuf_c_message_unpack (&ct__rpc__descriptor,
                                allocator, len, data);
}
void   ct__rpc__free_unpacked
                     (CTRPC *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ct__rpc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ct__rpc__header__field_descriptors[3] =
{
  {
    "msgId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CTRPC__Header, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "funcType",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CTRPC__Header, functype),
    &ct__rpc__func_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CTRPC__Header, checksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__header__field_indices_by_name[] = {
  2,   /* field[2] = checksum */
  1,   /* field[1] = funcType */
  0,   /* field[0] = msgId */
};
static const ProtobufCIntRange ct__rpc__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ct__rpc__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.Header",
  "Header",
  "CTRPC__Header",
  "",
  sizeof(CTRPC__Header),
  3,
  ct__rpc__header__field_descriptors,
  ct__rpc__header__field_indices_by_name,
  1,  ct__rpc__header__number_ranges,
  (ProtobufCMessageInit) ct__rpc__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__response__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CTRPC__Response, result),
    &ct__rpc__func_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultMsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CTRPC__Response, resultmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__response__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = resultMsg */
};
static const ProtobufCIntRange ct__rpc__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ct__rpc__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.Response",
  "Response",
  "CTRPC__Response",
  "",
  sizeof(CTRPC__Response),
  2,
  ct__rpc__response__field_descriptors,
  ct__rpc__response__field_indices_by_name,
  1,  ct__rpc__response__number_ranges,
  (ProtobufCMessageInit) ct__rpc__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__snd_creds__field_descriptors[1] =
{
  {
    "cred",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CTRPC__SndCreds, cred),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__snd_creds__field_indices_by_name[] = {
  0,   /* field[0] = cred */
};
static const ProtobufCIntRange ct__rpc__snd_creds__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__snd_creds__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.SndCreds",
  "SndCreds",
  "CTRPC__SndCreds",
  "",
  sizeof(CTRPC__SndCreds),
  1,
  ct__rpc__snd_creds__field_descriptors,
  ct__rpc__snd_creds__field_indices_by_name,
  1,  ct__rpc__snd_creds__number_ranges,
  (ProtobufCMessageInit) ct__rpc__snd_creds__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__req_asc_nonce__field_descriptors[1] =
{
  {
    "devId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CTRPC__ReqAscNonce, devid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__req_asc_nonce__field_indices_by_name[] = {
  0,   /* field[0] = devId */
};
static const ProtobufCIntRange ct__rpc__req_asc_nonce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__req_asc_nonce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.ReqAscNonce",
  "ReqAscNonce",
  "CTRPC__ReqAscNonce",
  "",
  sizeof(CTRPC__ReqAscNonce),
  1,
  ct__rpc__req_asc_nonce__field_descriptors,
  ct__rpc__req_asc_nonce__field_indices_by_name,
  1,  ct__rpc__req_asc_nonce__number_ranges,
  (ProtobufCMessageInit) ct__rpc__req_asc_nonce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__req_asc_nonce_resp__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CTRPC__ReqAscNonceResp, result),
    &ct__rpc__func_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CTRPC__ReqAscNonceResp, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__req_asc_nonce_resp__field_indices_by_name[] = {
  1,   /* field[1] = nonce */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange ct__rpc__req_asc_nonce_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ct__rpc__req_asc_nonce_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.ReqAscNonceResp",
  "ReqAscNonceResp",
  "CTRPC__ReqAscNonceResp",
  "",
  sizeof(CTRPC__ReqAscNonceResp),
  2,
  ct__rpc__req_asc_nonce_resp__field_descriptors,
  ct__rpc__req_asc_nonce_resp__field_indices_by_name,
  1,  ct__rpc__req_asc_nonce_resp__number_ranges,
  (ProtobufCMessageInit) ct__rpc__req_asc_nonce_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__asc_window__field_descriptors[1] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CTRPC__AscWindow, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__asc_window__field_indices_by_name[] = {
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange ct__rpc__asc_window__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__asc_window__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.AscWindow",
  "AscWindow",
  "CTRPC__AscWindow",
  "",
  sizeof(CTRPC__AscWindow),
  1,
  ct__rpc__asc_window__field_descriptors,
  ct__rpc__asc_window__field_indices_by_name,
  1,  ct__rpc__asc_window__number_ranges,
  (ProtobufCMessageInit) ct__rpc__asc_window__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__set_certs__field_descriptors[1] =
{
  {
    "certs",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CTRPC__SetCerts, certs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__set_certs__field_indices_by_name[] = {
  0,   /* field[0] = certs */
};
static const ProtobufCIntRange ct__rpc__set_certs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__set_certs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.SetCerts",
  "SetCerts",
  "CTRPC__SetCerts",
  "",
  sizeof(CTRPC__SetCerts),
  1,
  ct__rpc__set_certs__field_descriptors,
  ct__rpc__set_certs__field_indices_by_name,
  1,  ct__rpc__set_certs__number_ranges,
  (ProtobufCMessageInit) ct__rpc__set_certs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__add_cert__field_descriptors[1] =
{
  {
    "cert",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CTRPC__AddCert, cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__add_cert__field_indices_by_name[] = {
  0,   /* field[0] = cert */
};
static const ProtobufCIntRange ct__rpc__add_cert__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__add_cert__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.AddCert",
  "AddCert",
  "CTRPC__AddCert",
  "",
  sizeof(CTRPC__AddCert),
  1,
  ct__rpc__add_cert__field_descriptors,
  ct__rpc__add_cert__field_indices_by_name,
  1,  ct__rpc__add_cert__number_ranges,
  (ProtobufCMessageInit) ct__rpc__add_cert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__set_bckoff__field_descriptors[2] =
{
  {
    "lut",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTRPC__SetBckoff, n_lut),
    offsetof(CTRPC__SetBckoff, lut),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lut_decay",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTRPC__SetBckoff, n_lut_decay),
    offsetof(CTRPC__SetBckoff, lut_decay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__set_bckoff__field_indices_by_name[] = {
  0,   /* field[0] = lut */
  1,   /* field[1] = lut_decay */
};
static const ProtobufCIntRange ct__rpc__set_bckoff__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ct__rpc__set_bckoff__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.SetBckoff",
  "SetBckoff",
  "CTRPC__SetBckoff",
  "",
  sizeof(CTRPC__SetBckoff),
  2,
  ct__rpc__set_bckoff__field_descriptors,
  ct__rpc__set_bckoff__field_indices_by_name,
  1,  ct__rpc__set_bckoff__number_ranges,
  (ProtobufCMessageInit) ct__rpc__set_bckoff__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__set_serv_list__field_descriptors[1] =
{
  {
    "domain",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(CTRPC__SetServList, n_domain),
    offsetof(CTRPC__SetServList, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__set_serv_list__field_indices_by_name[] = {
  0,   /* field[0] = domain */
};
static const ProtobufCIntRange ct__rpc__set_serv_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__set_serv_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.SetServList",
  "SetServList",
  "CTRPC__SetServList",
  "",
  sizeof(CTRPC__SetServList),
  1,
  ct__rpc__set_serv_list__field_descriptors,
  ct__rpc__set_serv_list__field_indices_by_name,
  1,  ct__rpc__set_serv_list__number_ranges,
  (ProtobufCMessageInit) ct__rpc__set_serv_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ct__rpc__log_mode__field_descriptors[1] =
{
  {
    "isEnabled",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(CTRPC__LogMode, isenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__log_mode__field_indices_by_name[] = {
  0,   /* field[0] = isEnabled */
};
static const ProtobufCIntRange ct__rpc__log_mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ct__rpc__log_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC.LogMode",
  "LogMode",
  "CTRPC__LogMode",
  "",
  sizeof(CTRPC__LogMode),
  1,
  ct__rpc__log_mode__field_descriptors,
  ct__rpc__log_mode__field_indices_by_name,
  1,  ct__rpc__log_mode__number_ranges,
  (ProtobufCMessageInit) ct__rpc__log_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ct__rpc__func_type__enum_values_by_number[10] =
{
  { "RESPONSE", "CT__RPC__FUNC_TYPE__RESPONSE", 1 },
  { "SND_CREDS", "CT__RPC__FUNC_TYPE__SND_CREDS", 2 },
  { "REQ_ASC_NONCE", "CT__RPC__FUNC_TYPE__REQ_ASC_NONCE", 3 },
  { "REQ_ASC_NONCE_RESP", "CT__RPC__FUNC_TYPE__REQ_ASC_NONCE_RESP", 4 },
  { "ASC_WINDOW", "CT__RPC__FUNC_TYPE__ASC_WINDOW", 5 },
  { "SET_CERTS", "CT__RPC__FUNC_TYPE__SET_CERTS", 6 },
  { "ADD_CERT", "CT__RPC__FUNC_TYPE__ADD_CERT", 7 },
  { "SET_BCKOFF", "CT__RPC__FUNC_TYPE__SET_BCKOFF", 8 },
  { "SET_SERV_LIST", "CT__RPC__FUNC_TYPE__SET_SERV_LIST", 9 },
  { "LOG_MODE", "CT__RPC__FUNC_TYPE__LOG_MODE", 10 },
};
static const ProtobufCIntRange ct__rpc__func_type__value_ranges[] = {
{1, 0},{0, 10}
};
static const ProtobufCEnumValueIndex ct__rpc__func_type__enum_values_by_name[10] =
{
  { "ADD_CERT", 6 },
  { "ASC_WINDOW", 4 },
  { "LOG_MODE", 9 },
  { "REQ_ASC_NONCE", 2 },
  { "REQ_ASC_NONCE_RESP", 3 },
  { "RESPONSE", 0 },
  { "SET_BCKOFF", 7 },
  { "SET_CERTS", 5 },
  { "SET_SERV_LIST", 8 },
  { "SND_CREDS", 1 },
};
const ProtobufCEnumDescriptor ct__rpc__func_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CT_RPC.FuncType",
  "FuncType",
  "CTRPC__FuncType",
  "",
  10,
  ct__rpc__func_type__enum_values_by_number,
  10,
  ct__rpc__func_type__enum_values_by_name,
  1,
  ct__rpc__func_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ct__rpc__func_result__enum_values_by_number[4] =
{
  { "OK", "CT__RPC__FUNC_RESULT__OK", 1 },
  { "CHKSUM_ERR", "CT__RPC__FUNC_RESULT__CHKSUM_ERR", 2 },
  { "STORE_ERR", "CT__RPC__FUNC_RESULT__STORE_ERR", 3 },
  { "GEN_ERR", "CT__RPC__FUNC_RESULT__GEN_ERR", 4 },
};
static const ProtobufCIntRange ct__rpc__func_result__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ct__rpc__func_result__enum_values_by_name[4] =
{
  { "CHKSUM_ERR", 1 },
  { "GEN_ERR", 3 },
  { "OK", 0 },
  { "STORE_ERR", 2 },
};
const ProtobufCEnumDescriptor ct__rpc__func_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CT_RPC.FuncResult",
  "FuncResult",
  "CTRPC__FuncResult",
  "",
  4,
  ct__rpc__func_result__enum_values_by_number,
  4,
  ct__rpc__func_result__enum_values_by_name,
  1,
  ct__rpc__func_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ct__rpc__field_descriptors[11] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, header),
    &ct__rpc__header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, response),
    &ct__rpc__response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sndCreds",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, sndcreds),
    &ct__rpc__snd_creds__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqAscNonce",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, reqascnonce),
    &ct__rpc__req_asc_nonce__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqAscNonceResp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, reqascnonceresp),
    &ct__rpc__req_asc_nonce_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ascWindow",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, ascwindow),
    &ct__rpc__asc_window__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setCerts",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, setcerts),
    &ct__rpc__set_certs__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addCert",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, addcert),
    &ct__rpc__add_cert__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setBckoff",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, setbckoff),
    &ct__rpc__set_bckoff__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setServList",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, setservlist),
    &ct__rpc__set_serv_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logMode",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CTRPC, logmode),
    &ct__rpc__log_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ct__rpc__field_indices_by_name[] = {
  7,   /* field[7] = addCert */
  5,   /* field[5] = ascWindow */
  0,   /* field[0] = header */
  10,   /* field[10] = logMode */
  3,   /* field[3] = reqAscNonce */
  4,   /* field[4] = reqAscNonceResp */
  1,   /* field[1] = response */
  8,   /* field[8] = setBckoff */
  6,   /* field[6] = setCerts */
  9,   /* field[9] = setServList */
  2,   /* field[2] = sndCreds */
};
static const ProtobufCIntRange ct__rpc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ct__rpc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CT_RPC",
  "CTRPC",
  "CTRPC",
  "",
  sizeof(CTRPC),
  11,
  ct__rpc__field_descriptors,
  ct__rpc__field_indices_by_name,
  1,  ct__rpc__number_ranges,
  (ProtobufCMessageInit) ct__rpc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
