/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Espressif IoT Development Framework Configuration
 *
 * Edited by Xively - Fields not required at libxively.a and wolfssl.a build
 * time have been removed
 *
 */
#define CONFIG_FREERTOS_BREAK_ON_SCHEDULER_START_JTAG 1
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION 1
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY 1
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_CORETIMER_0 1
#define CONFIG_FREERTOS_HZ 100

#define CONFIG_TCP_WND_DEFAULT 5744
#define CONFIG_TCP_OVERSIZE_MSS 1
#define CONFIG_TCP_QUEUE_OOSEQ 1
#define CONFIG_TCP_MAXRTX 12
#define CONFIG_TCP_MSS 1436

#define CONFIG_LWIP_THREAD_LOCAL_STORAGE_INDEX 0
#define CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
#define CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1
#define CONFIG_LWIP_MAX_SOCKETS 10

#define CONFIG_WL_SECTOR_SIZE 4096
#define CONFIG_WL_SECTOR_SIZE_4096 1

#define CONFIG_FATFS_CODEPAGE 437
#define CONFIG_FATFS_CODEPAGE_437 1
#define CONFIG_FATFS_LFN_HEAP 1
#define CONFIG_FATFS_MAX_LFN 255

#define CONFIG_SPIFFS_USE_MAGIC_LENGTH 1
#define CONFIG_SPIFFS_CACHE_WR 1
#define CONFIG_SPIFFS_CACHE 1
#define CONFIG_SPIFFS_CHECK_DBG 1
#define CONFIG_SPIFFS_TEST_VISUALISATION 1
#define CONFIG_SPIFFS_CACHE_DBG 1
#define CONFIG_SPIFFS_USE_MAGIC 1
#define CONFIG_SPIFFS_PAGE_CHECK 1
#define CONFIG_SPIFFS_GC_DBG 1
#define CONFIG_SPIFFS_GC_MAX_RUNS 10
#define CONFIG_SPIFFS_DBG 1
#define CONFIG_SPIFFS_OBJ_NAME_LEN 32
#define CONFIG_SPIFFS_API_DBG 1
